[default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/"
]
optimizer = true
optimizer_runs = 200

[profile.release]
optimizer = true
optimizer_runs = 200

[profile.coverage]
optimizer = false

[remappings]
"@openzeppelin" = "lib/openzeppelin-contracts/contracts"
"@chainlink" = "lib/chainlink-brownie-contracts/contracts"

[networks]
[forge.sepolia]
url = "https://sepolia.infura.io/v3/$INFURA_API_KEY"
mnemonic = "test test test test test test test test test test test junk"

[eth_rpc_urls]
sepolia = "https://sepolia.infura.io/v3/$INFURA_API_KEY"
