[default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/contracts/",
  "@chainlink/=lib/foundry-chainlink-toolkit/src/",
]
optimizer = true
optimizer_runs = 200

[profile.release]
optimizer = true
optimizer_runs = 200

[profile.coverage]
optimizer = false

[remappings]
"@openzeppelin" = "lib/openzeppelin-contracts/contracts"
"@chainlink" = "lib/foundry-chainlink-toolkit/src"

[networks]
[forge.sepolia]
url = "https://sepolia.infura.io/v3/$INFURA_API_KEY"
mnemonic = "test test test test test test test test test test test junk"

[eth_rpc_urls]
sepolia = "https://sepolia.infura.io/v3/$INFURA_API_KEY"
